kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.14
    commands:
      - go build
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run

notify:
  image: drillster/drone-email
  host: mailrelay
  port: 25
  skip_verify: true
  from: ob@cs.hm.edu
  when:
    status: [changed, failure]
